-- MySQL Script generated by MySQL Workbench
-- 11/19/16 16:52:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shop` ;

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`statusType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`statusType` ;

CREATE TABLE IF NOT EXISTS `shop`.`statusType` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `statusTypeName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`status` ;

CREATE TABLE IF NOT EXISTS `shop`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `statusType_id` INT NOT NULL COMMENT '',
  `statusName` VARCHAR(45) NOT NULL COMMENT '',
  `icon` VARCHAR(45) NULL COMMENT '',
  `ket` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`, `statusType_id`)  COMMENT '',
  INDEX `fk_status_statusType1_idx` (`statusType_id` ASC)  COMMENT '',
  CONSTRAINT `fk_status_statusType1`
    FOREIGN KEY (`statusType_id`)
    REFERENCES `shop`.`statusType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`produkType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`produkType` ;

CREATE TABLE IF NOT EXISTS `shop`.`produkType` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `produkTypeName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`produk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`produk` ;

CREATE TABLE IF NOT EXISTS `shop`.`produk` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `status_id` INT NOT NULL COMMENT '',
  `produkType_id` INT NOT NULL COMMENT '',
  `namaProduk` VARCHAR(45) NULL COMMENT '',
  `harga` DOUBLE NULL COMMENT '',
  `stok` INT NULL COMMENT '',
  `createOn` DATE NULL COMMENT '',
  `createBy` VARCHAR(11) NULL COMMENT '',
  `modifOn` DATE NULL COMMENT '',
  `modifBy` VARCHAR(11) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_produk_status1_idx` (`status_id` ASC)  COMMENT '',
  INDEX `fk_produk_produkType1_idx` (`produkType_id` ASC)  COMMENT '',
  CONSTRAINT `fk_produk_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `shop`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produk_produkType1`
    FOREIGN KEY (`produkType_id`)
    REFERENCES `shop`.`produkType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`trxType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`trxType` ;

CREATE TABLE IF NOT EXISTS `shop`.`trxType` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `typeName` VARCHAR(45) NOT NULL COMMENT '',
  `Init` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`supplierType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`supplierType` ;

CREATE TABLE IF NOT EXISTS `shop`.`supplierType` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `typeName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`supplier` ;

CREATE TABLE IF NOT EXISTS `shop`.`supplier` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `status_id` INT NOT NULL COMMENT '',
  `namaSupplier` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `alamat` TEXT NULL COMMENT '',
  `kontak` VARCHAR(45) NULL COMMENT '',
  `joinOn` DATE NULL COMMENT '',
  `supplierType_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_supplier_status1_idx` (`status_id` ASC)  COMMENT '',
  INDEX `fk_supplier_supplierType1_idx` (`supplierType_id` ASC)  COMMENT '',
  CONSTRAINT `fk_supplier_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `shop`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_supplierType1`
    FOREIGN KEY (`supplierType_id`)
    REFERENCES `shop`.`supplierType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`trxHeader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`trxHeader` ;

CREATE TABLE IF NOT EXISTS `shop`.`trxHeader` (
  `id` VARCHAR(11) NOT NULL COMMENT '',
  `status_id` INT NOT NULL COMMENT '',
  `createBy` VARCHAR(45) NULL COMMENT '',
  `createOn` DATE NULL COMMENT '',
  `modifBy` VARCHAR(45) NULL COMMENT '',
  `modifOn` DATE NULL COMMENT '',
  `trxType_id` INT NOT NULL COMMENT '',
  `confirmedBy` VARCHAR(45) NULL COMMENT '',
  `supplier_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_trxHeader_status1_idx` (`status_id` ASC)  COMMENT '',
  INDEX `fk_trxHeader_trxType1_idx` (`trxType_id` ASC)  COMMENT '',
  INDEX `fk_trxHeader_supplier1_idx` (`supplier_id` ASC)  COMMENT '',
  CONSTRAINT `fk_trxHeader_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `shop`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trxHeader_trxType1`
    FOREIGN KEY (`trxType_id`)
    REFERENCES `shop`.`trxType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trxHeader_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `shop`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`trxDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`trxDetail` ;

CREATE TABLE IF NOT EXISTS `shop`.`trxDetail` (
  `id` VARCHAR(11) NOT NULL COMMENT '',
  `trxHeader_id` VARCHAR(11) NOT NULL COMMENT '',
  `qty` INT NULL COMMENT '',
  `harga` DOUBLE NULL COMMENT '',
  `produk_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_trxDetail_trxHeader1_idx` (`trxHeader_id` ASC)  COMMENT '',
  INDEX `fk_trxDetail_produk1_idx` (`produk_id` ASC)  COMMENT '',
  CONSTRAINT `fk_trxDetail_trxHeader1`
    FOREIGN KEY (`trxHeader_id`)
    REFERENCES `shop`.`trxHeader` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trxDetail_produk1`
    FOREIGN KEY (`produk_id`)
    REFERENCES `shop`.`produk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`departemen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`departemen` ;

CREATE TABLE IF NOT EXISTS `shop`.`departemen` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `depName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`jabatan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`jabatan` ;

CREATE TABLE IF NOT EXISTS `shop`.`jabatan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'kode Dep dan no urut',
  `jabatanName` VARCHAR(45) NOT NULL COMMENT '',
  `departemen_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_jabatan_departemen1_idx` (`departemen_id` ASC)  COMMENT '',
  CONSTRAINT `fk_jabatan_departemen1`
    FOREIGN KEY (`departemen_id`)
    REFERENCES `shop`.`departemen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`karyawan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`karyawan` ;

CREATE TABLE IF NOT EXISTS `shop`.`karyawan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'kode jabatan dan no urut',
  `status_id` INT NOT NULL COMMENT '',
  `namaDepan` VARCHAR(45) NOT NULL COMMENT '',
  `namaBelakang` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `dob` DATE NOT NULL COMMENT '',
  `gender` VARCHAR(1) NOT NULL COMMENT '',
  `kontak` VARCHAR(25) NOT NULL COMMENT '',
  `joinOn` DATE NOT NULL COMMENT '',
  `jabatan_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_karyawan_status1_idx` (`status_id` ASC)  COMMENT '',
  INDEX `fk_karyawan_jabatan1_idx` (`jabatan_id` ASC)  COMMENT '',
  CONSTRAINT `fk_karyawan_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `shop`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_karyawan_jabatan1`
    FOREIGN KEY (`jabatan_id`)
    REFERENCES `shop`.`jabatan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`TrxReject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`TrxReject` ;

CREATE TABLE IF NOT EXISTS `shop`.`TrxReject` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `trxDetail_id` VARCHAR(11) NOT NULL COMMENT '',
  `qty` INT NOT NULL COMMENT '',
  `alasan` TEXT NULL COMMENT '',
  `produk_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_TrxReject_trxDetail1_idx` (`trxDetail_id` ASC)  COMMENT '',
  INDEX `fk_TrxReject_produk1_idx` (`produk_id` ASC)  COMMENT '',
  CONSTRAINT `fk_TrxReject_trxDetail1`
    FOREIGN KEY (`trxDetail_id`)
    REFERENCES `shop`.`trxDetail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TrxReject_produk1`
    FOREIGN KEY (`produk_id`)
    REFERENCES `shop`.`produk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `shop`.`statusType`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`statusType` (`id`, `statusTypeName`) VALUES (1221, 'Aktifvasi');
INSERT INTO `shop`.`statusType` (`id`, `statusTypeName`) VALUES (1222, 'Pembayaran');
INSERT INTO `shop`.`statusType` (`id`, `statusTypeName`) VALUES (1223, 'Transaksi');

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`status`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`status` (`id`, `statusType_id`, `statusName`, `icon`, `ket`) VALUES (11, 1221, 'AKTIF', NULL, 'Status Aktif');
INSERT INTO `shop`.`status` (`id`, `statusType_id`, `statusName`, `icon`, `ket`) VALUES (22, 1221, 'NON-AKTIF', NULL, 'Status Aktif');
INSERT INTO `shop`.`status` (`id`, `statusType_id`, `statusName`, `icon`, `ket`) VALUES (33, 1222, 'DIBAYAR', NULL, 'Status Pembayaran Transaksi');
INSERT INTO `shop`.`status` (`id`, `statusType_id`, `statusName`, `icon`, `ket`) VALUES (44, 1222, 'BELUM DIBAYAR', NULL, 'Status Pembayaran  Transaksi');
INSERT INTO `shop`.`status` (`id`, `statusType_id`, `statusName`, `icon`, `ket`) VALUES (55, 1223, 'GAGAL', NULL, 'Status Transaksi');
INSERT INTO `shop`.`status` (`id`, `statusType_id`, `statusName`, `icon`, `ket`) VALUES (66, 1223, 'SUKSES', NULL, 'Status Transaksi');
INSERT INTO `shop`.`status` (`id`, `statusType_id`, `statusName`, `icon`, `ket`) VALUES (77, 1223, 'PENDING', NULL, 'Status Transaksi');

COMMIT;

